"""empty message

Revision ID: 650b5e029bba
Revises: 
Create Date: 2024-10-19 12:09:41.163092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650b5e029bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('own', schema=None) as batch_op:
        batch_op.add_column(sa.Column('many', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('own', schema=None) as batch_op:
        batch_op.drop_column('many')

    # ### end Alembic commands ###
